name: intranavigator
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cloud_firestore: ^4.2.0
  cross_connectivity: ^3.0.5
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^8.0.0
  equatable: ^2.0.5
  fake_cloud_firestore: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  injectable: ^2.1.0
  json_annotation: ^4.7.0
  mockito: ^5.3.2
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  injectable_generator: ^2.1.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
